<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css.css">
    <script src="https://use.fontawesome.com/fd4530cf2.js"></script>

  </head>
  <body>

    <nav class="navbar navbar-expand bg-secondary navbar-light">

      <img src="logo.svg" class="img-logo" alt="">
      <a class="navbar-brand" href="#">PC Mallorca</a>


      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>


        <form class="form-inline mx-auto" action="/action_page.php">
          <input class="form-control" type="text" placeholder="Search">
          <button class="btn btn-success" type="submit">Search</button>
        </form>


      <i class="fa fa-user-circle fa-2x" aria-hidden="true"></i>
      <i class="fa fa-shopping-cart fa-2x" aria-hidden="true"></i>

    </nav>


  </body>
</html>
