<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title></title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" href="css.css">
  <!--<script src="https://use.fontawesome.com/fd4530cf2.js"></script>-->
<script type="text/javascript">

</script>
</head>

<body>

  <div class="bg-grisOscuro">
    <div class="container">
      <nav class="navbar navbar-expand  navbar-light">

        <img src="logo1.png" class="img-logo mr-1" alt="">
        <a class="navbar-brand" href="#">Components Bear PC</a>


        <form class="form-inline mx-auto" action="/action_page.php">
          <input class="form-control" type="text" placeholder="Search">
          <button class="btn btn-danger" type="submit">Search</button>
        </form>

        <span>Account</span>
        <i class="fa fa-user-circle fa-2x mr-2 ml-2" aria-hidden="true"></i>
        <span>My order </span>
        <i class="fa fa-shopping-cart fa-2x" aria-hidden="true"></i>
      </nav>
    </div>
  </div>

  <div class="container">


    <!-- Bootstrap row -->
    <div class="row" id="body-row">
      <!-- Sidebar -->
      <div id="sidebar-container" class="sidebar-expanded d-none d-md-block col-2">
        <!-- d-* hiddens the Sidebar in smaller devices. Its itens can be kept on the Navbar 'Menu' -->
        <!-- Bootstrap List Group -->
        <ul class="list-group">
          <!-- Separator with title -->
          <li class="list-group-item sidebar-separator-title text-muted d-flex align-items-center menu-collapsed">
            <small>MAIN MENU</small>
          </li>
          <!-- /END Separator -->
          <!-- Menu with submenu -->
          <a href="#submenu1" data-toggle="collapse" aria-expanded="false" class="bg-grisa list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-start align-items-center">
              <span class="fa fa-dashboard fa-fw mr-3"></span>
              <span class="menu-collapsed text-dark">Ordenadores</span>
              <span class="submenu-icon ml-auto"></span>
            </div>
          </a>
          <!-- Submenu content -->
          <div id='submenu1' class="collapse sidebar-submenu">
            <a href="#" class="list-group-item list-group-item-action bg-dark text-white">
                    <span class="menu-collapsed">Portátiles</span>
                </a>
            <a href="#" class="list-group-item list-group-item-action bg-dark text-white">
                    <span class="menu-collapsed">Gaming</span>
                </a>
            <a href="#" class="list-group-item list-group-item-action bg-dark text-white">
                    <span class="menu-collapsed">Sobremesa</span>
                </a>
          </div>
          <a href="#submenu2" data-toggle="collapse" aria-expanded="false" class="bg-dark list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-start align-items-center">
              <span class="fa fa-user fa-fw mr-3"></span>
              <span class="menu-collapsed">Componentes</span>
              <span class="submenu-icon ml-auto"></span>
            </div>
          </a>
          <!-- Submenu content -->
          <div id='submenu2' class="collapse sidebar-submenu">
            <a href="#" class="list-group-item list-group-item-action bg-dark text-white">
                    <span class="menu-collapsed">Procesadores</span>
                </a>
            <a href="#" class="list-group-item list-group-item-action bg-dark text-white">
                    <span class="menu-collapsed">Tarjetas gráficas</span>
                </a>
          </div>
          <!-- fin submenu content -->
          <a href="#submenu3" data-toggle="collapse" aria-expanded="false" class="bg-dark list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-start align-items-center">
              <span class="fa fa-tasks fa-fw mr-3"></span>
              <span class="menu-collapsed">Periféricos</span>
              <span class="submenu-icon ml-auto"></span>
            </div>
          </a>

          <!-- Submenu content -->
          <div id='submenu3' class="collapse sidebar-submenu">
            <a href="#" class="list-group-item list-group-item-action bg-dark text-white">
                    <span class="menu-collapsed">Teclados</span>
                </a>
            <a href="#" class="list-group-item list-group-item-action bg-dark text-white">
                    <span class="menu-collapsed">Monitores</span>
                </a>
          </div>

          <!-- Separator with title -->
          <li class="list-group-item sidebar-separator-title text-muted d-flex align-items-center menu-collapsed">
            <small>Mi perfil</small>
          </li>
          <!-- /END Separator -->
          <a href="#" class="bg-dark list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-start align-items-center">
              <span class="fa fa-calendar fa-fw mr-3"></span>
              <span class="menu-collapsed">Perfil</span>
            </div>
          </a>
          <a href="#" class="bg-dark list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-start align-items-center">
              <span class="fa fa-envelope-o fa-fw mr-2"></span>
              <span class="menu-collapsed">Administrar <span class="badge badge-pill badge-primary ml-2">5</span></span>
            </div>
          </a>


        </ul>
        <!-- List Group END-->
      </div>
      <!-- sidebar-container END -->

      <div class="p-0 col-10 col-md-10 hola">
        <div id="demo" class="carousel slide" data-ride="carousel">
          <ul class="carousel-indicators">
            <li data-target="#demo" data-slide-to="0" class="active"></li>
            <li data-target="#demo" data-slide-to="1"></li>
            <li data-target="#demo" data-slide-to="2"></li>
          </ul>
          <div class="carousel-inner ">
            <div class="carousel-item active">
              <img src="../imgs/p1.jpg" class="img-fluid hola" style="width:100%;">
              <div class="carousel-caption">
                <h3>Los Angeles</h3>
                <p>We had such a great time in LA!</p>
              </div>
            </div>
            <div class="carousel-item">
              <img src="../imgs/p2.png" alt="Chicago" class="img-fluid bg-dark hola" style="width:100%;">
              <div class="carousel-caption">
                <h3>Chicago</h3>
                <p>Thank you, Chicago!</p>
              </div>
            </div>
            <div class="carousel-item">
              <img src="../imgs/4.png" alt="New York" class="img-fluid hola bg-dark" style="width:100%;">
              <div class="carousel-caption">
                <h3>New York</h3>
                <p>We love the Big Apple!</p>
              </div>
            </div>
          </div>
          <a class="carousel-control-prev" href="#demo" data-slide="prev">
      <span class="carousel-control-prev-icon"></span>
    </a>
          <a class="carousel-control-next" href="#demo" data-slide="next">
      <span class="carousel-control-next-icon"></span>
    </a>
        </div>
      </div>

      <div class="col-sm-6 col-md-4 col-lg-3 mt-4">
        <div class="card card-inverse card-info">
          <img class="card-img-top" src="http://success-at-work.com/wp-content/uploads/2015/04/free-stock-photos.gif">
          <div class="card-block">
            <figure class="profile">
              <img src="http://success-at-work.com/wp-content/uploads/2015/04/free-stock-photos.gif" class="profile-avatar" alt="">
            </figure>
            <h4 class="card-title mt-3">Tawshif Ahsan Khan</h4>
            <div class="meta card-text">
              <a>Friends</a>
            </div>
            <div class="card-text">
              Tawshif is a web designer living in Bangladesh.
            </div>
          </div>
          <div class="card-footer">
            <small>Last updated 3 mins ago</small>
            <button class="btn btn-info float-right btn-sm">Follow</button>
          </div>
        </div>
      </div>

    </div>


</body>

</html>
