<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title></title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" href="views/css.css">
  <!--<script src="https://use.fontawesome.com/fd4530cf2.js"></script>-->


</head>

<body>


  <nav class="navbar navbar-expand  navbar-light bg-grisOscuro">

    <img src="views/logo1.png" class="img-logo mr-1" alt="">
    <a class="navbar-brand" href="#">Components Bear PC</a>

    <button type="button" data-toggle="dropdown" class="btn-danger">Categorias</button>


    <div class="dropdown-menu dropdown-mega">
      <div class="row container">
        <div class="col-md-4 dropdown-mega--column">
          <h4 class="dropdown-mega--menu-header">Componentes</h4>
          <div class="list-group">
            <a href="#" class="list-group-item list-group-item-action">These Boots Are Made For Walking</a>
            <a href="#" class="list-group-item list-group-item-action disabled">Eleanor, Put Your Boots On</a>
            <a href="#" class="list-group-item list-group-item-action">Puss 'n' Boots</a>
            <a href="#" class="list-group-item list-group-item-action">Die With Your Boots On</a>
            <a href="#" class="list-group-item list-group-item-action">Fairies Wear Boots</a>
          </div>
        </div>
        <div class="col-md-4 dropdown-mega--column">
          <h4 class="dropdown-mega--menu-header">Periféricos</h4>
          <div class="list-group">
            <a href="#" class="list-group-item list-group-item-action">These Boots Are Made For Walking</a>
            <a href="#" class="list-group-item list-group-item-action disabled">Eleanor, Put Your Boots On</a>
            <a href="#" class="list-group-item list-group-item-action">Puss 'n' Boots</a>
            <a href="#" class="list-group-item list-group-item-action">Die With Your Boots On</a>
            <a href="#" class="list-group-item list-group-item-action">Fairies Wear Boots</a>
          </div>
        </div>
        <div class="col-md-4 dropdown-mega--column">
          <h4 class="dropdown-mega--menu-header">Ordenadores</h4>
          <div class="list-group">
            <a href="#" class="list-group-item list-group-item-action">These Boots Are Made For Walking</a>
            <a href="#" class="list-group-item list-group-item-action disabled">Eleanor, Put Your Boots On</a>
            <a href="#" class="list-group-item list-group-item-action">Puss 'n' Boots</a>
            <a href="#" class="list-group-item list-group-item-action">Die With Your Boots On</a>
            <a href="#" class="list-group-item list-group-item-action">Fairies Wear Boots</a>
          </div>
        </div>
      </div>
      <!--.row-->
    </div>
    <!--.dropdown-menu .dropdown-mega-->

    <form class="form-inline mx-auto" action="/action_page.php">
      <input class="form-control" type="text" placeholder="Search">
    </form>

    <span>Account</span>
    <i class="fa fa-user-circle fa-2x mr-2 ml-2" aria-hidden="true"></i>
    <span>My order </span>
    <i class="fa fa-shopping-cart fa-2x" aria-hidden="true"></i>
  </nav>




<div class="bg-grisa myDiv">


  <div class="container text-center">



    <div id="demo" class="carousel slide" data-ride="carousel">
      <ul class="carousel-indicators">
        <li data-target="#demo" data-slide-to="0" class="active"></li>
        <li data-target="#demo" data-slide-to="1"></li>
        <li data-target="#demo" data-slide-to="2"></li>
      </ul>
      <div class="carousel-inner ">
        <div class="carousel-item active">
          <img src="views/imgs/p1.jpg" class="img-fluid hola" style="width:100%;">
          <div class="carousel-caption">
            <h3>Los Angeles</h3>
            <p>We had such a great time in LA!</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="views/imgs/p2.png" alt="Chicago" class="img-fluid bg-dark hola" style="width:100%;">
          <div class="carousel-caption">
            <h3>Chicago</h3>
            <p>Thank you, Chicago!</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="views/imgs/4.png" alt="New York" class="img-fluid hola bg-dark" style="width:100%;">
          <div class="carousel-caption">
            <h3>New York</h3>
            <p>We love the Big Apple!</p>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#demo" data-slide="prev">
  <span class="carousel-control-prev-icon"></span>
  </a>
      <a class="carousel-control-next" href="#demo" data-slide="next">
  <span class="carousel-control-next-icon"></span>
  </a>
    </div>


    <div class="container ">
      <div class="row">
        <?php foreach ($datos as $dato) { ?>
        <div class="col-sm- col-md-4 col-lg-4 mt-4 minimo">

          <div class="card">
            <img class="card-img-top" src="http://success-at-work.com/wp-content/uploads/2015/04/free-stock-photos.gif">
            <div class="card-block">
              <figure class="profile">
                <img src="http://success-at-work.com/wp-content/uploads/2015/04/free-stock-photos.gif" class="profile-avatar" alt="">
              </figure>
              <h4 class="card-title mt-3"><?php echo $dato['SHORTDESCRIPTION'] ?></h4>
              <div class="meta">
                <a>Friends</a>
              </div>
              <div class="card-text">
                <?php echo $dato['PRICE'] ?>
              </div>
            </div>
            <div class="card-footer">
              <small> <?php

              if ($dato['STOCK'] > 5) { ?>
              <span style="color:orange"> <?php echo "Quedan pocos en stock";}
              ?></span>

            </small>

              <button class="btn btn-secondary float-right btn-sm jeje">Comprar</button>
            </div>
          </div>
        </div>
        <?php } ?>


      </div>
    </div>
  </div>









</body>

</html>
