<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Log in</title>
  </head>
  <body>
    <div class="form">
      <form action= "index.php?controller=usuarios&action=login" method="post">
        <h1>Log in</h1>
        Usuario: <input type="text"   name="usuario" value="" ><br>
        Conraeña:   <input type="text"   name="password"   value="" ><br>
       	<input type="submit" value="Log in">
      </form>
    </div>
  </body>
</html>
