<div class="bg-grisa myDiv" >


      <div class="container text-center">

           <div class="container ">
            <div class="row">
                <?php foreach ($data['products'] as $product) { ?>
                    <div class="col-sm- col-md-4 col-lg-4 mt-4 minimo">

                        <div class="card">
                            <img class="card-img-top" src="<?php echo $product['URL'];?>">
                            <div class="card-block">
                                <figure class="profile">
                                    <img src="http://success-at-work.com/wp-content/uploads/2015/04/free-stock-photos.gif" class="profile-avatar" alt="">
                                </figure>
                                <h4 class="card-title mt-3"><?php echo $product['SHORTDESCRIPTION'];?></h4>
                                <div class="meta">
                                    <a></a>
                                </div>
                                <div class="card-text">
                                    <?php echo $product['PRICE'];?>
                                </div>
                            </div>
                            <div class="card-footer">
                                <small> <?php if ($product['STOCK'] == 0) { ?>
                                        <span style="color:red"> <?php echo "No quedan productos"; ?></span>
                                    <?php } elseif ($product['STOCK'] < 5) {
                                        ?>
                                        <span style="color:orange"> <?php echo "Quedan pocos en stock"; ?></span>
                                    <?php } ?>

                                </small>
                                <form action="?controller=cart&action=addToCart" method="POST">
                                <button name="id" value="<?php echo $product['ID']?>" class="btn btn-secondary float-right btn-sm jeje">Comprar</button>
                                </form>

                            </div>
                        </div>
                    </div>
                <?php } ?>

            </div>
        </div>

        <!-- cierro div container -->
    </div>

    <!-- sidebar -->

    <!-- cierro div bg -->
</div>

</body>

</html>
